### ISSUE TITLE
Tickets don't get the correct name set / auto-assignment no longer works

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#978]
Example:

![image](https://user-images.githubusercontent.com/6735498/58013750-9366a800-7af7-11e9-9a40-e356c4c319ef.png)

We are seeing this for all tickets sold for EP2019 in the Django admin.

**Comment by malemburg** [comment]
This is the logic (and function) we need to apply when assigning tickets: https://github.com/EuroPython/epcon/blob/ep2019/p3/utils.py#L36

This function of the same name in the conference package is not sufficient: https://github.com/EuroPython/epcon/blob/ep2019/conference/tickets.py#L4

It seems that we are not getting auto-assigned tickets anymore, because this listener no longer triggers: https://github.com/EuroPython/epcon/blob/ep2019/p3/listeners.py#L123

**Comment by umgelurgel** [comment]
Fixed in https://github.com/EuroPython/epcon/pull/998

**Comment by malemburg** [comment]
The change is not sufficient, since it still doesn't use the standard function we have for this: https://github.com/EuroPython/epcon/blob/ep2019/p3/utils.py#L36

**Comment by malemburg** [comment]
The other function of the same name need to go away to stop the confusion it is causing: https://github.com/EuroPython/epcon/blob/ep2019/conference/tickets.py#L4

**Comment by malemburg** [comment]
The "Assign Ticket" function in the user panel also needs to show the assigned email address. Even when this is set in the backend, it doesn't show the value.

**Comment by malemburg** [comment]
Assigned all tickets to buyers.

Will open a new ticket for the Assign Ticket issue.
